// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/metadata/proto/metadata.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Encryption int32

const (
	Encryption_NONE    Encryption = 0 // No encryption
	Encryption_RCLONE  Encryption = 1 // Rclone encryption
	Encryption_HEADERS Encryption = 2 // Headers encryption
	Encryption_AES     Encryption = 3 // Generic AES-CBC encryption (for RAR, 7z, etc.)
)

// Enum value maps for Encryption.
var (
	Encryption_name = map[int32]string{
		0: "NONE",
		1: "RCLONE",
		2: "HEADERS",
		3: "AES",
	}
	Encryption_value = map[string]int32{
		"NONE":    0,
		"RCLONE":  1,
		"HEADERS": 2,
		"AES":     3,
	}
)

func (x Encryption) Enum() *Encryption {
	p := new(Encryption)
	*p = x
	return p
}

func (x Encryption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encryption) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_metadata_proto_metadata_proto_enumTypes[0].Descriptor()
}

func (Encryption) Type() protoreflect.EnumType {
	return &file_internal_metadata_proto_metadata_proto_enumTypes[0]
}

func (x Encryption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encryption.Descriptor instead.
func (Encryption) EnumDescriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{0}
}

// FileStatus represents the health status of a file
type FileStatus int32

const (
	FileStatus_FILE_STATUS_UNSPECIFIED FileStatus = 0
	FileStatus_FILE_STATUS_HEALTHY     FileStatus = 1 // All segments available and file is complete
	FileStatus_FILE_STATUS_CORRUPTED   FileStatus = 3 // Segments missing or corrupted
	FileStatus_FILE_STATUS_DEGRADED    FileStatus = 4 // Media payload segments missing: playable with glitches, stays visible/streamable (2 was the removed PARTIAL — do not reuse)
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "FILE_STATUS_UNSPECIFIED",
		1: "FILE_STATUS_HEALTHY",
		3: "FILE_STATUS_CORRUPTED",
		4: "FILE_STATUS_DEGRADED",
	}
	FileStatus_value = map[string]int32{
		"FILE_STATUS_UNSPECIFIED": 0,
		"FILE_STATUS_HEALTHY":     1,
		"FILE_STATUS_CORRUPTED":   3,
		"FILE_STATUS_DEGRADED":    4,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_metadata_proto_metadata_proto_enumTypes[1].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_internal_metadata_proto_metadata_proto_enumTypes[1]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{1}
}

// SegmentData contains Usenet segment information with byte offsets
type SegmentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentSize   int64                  `protobuf:"varint,1,opt,name=segment_size,json=segmentSize,proto3" json:"segment_size,omitempty"` // Size of the segment in bytes
	StartOffset   int64                  `protobuf:"varint,3,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"` // Start byte offset in the data stream
	EndOffset     int64                  `protobuf:"varint,4,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`       // End byte offset in the data stream
	Id            string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`                                       // Usenet message ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentData) Reset() {
	*x = SegmentData{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentData) ProtoMessage() {}

func (x *SegmentData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentData.ProtoReflect.Descriptor instead.
func (*SegmentData) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *SegmentData) GetSegmentSize() int64 {
	if x != nil {
		return x.SegmentSize
	}
	return 0
}

func (x *SegmentData) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *SegmentData) GetEndOffset() int64 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *SegmentData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Par2FileReference stores information about PAR2 repair files
type Par2FileReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                          // PAR2 filename (e.g., "movie.par2", "movie.vol01+02.par2")
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`         // Size of the PAR2 file in bytes
	SegmentData   []*SegmentData         `protobuf:"bytes,3,rep,name=segment_data,json=segmentData,proto3" json:"segment_data,omitempty"` // Usenet segments containing PAR2 data
	SegmentRefs   []*SegmentRef          `protobuf:"bytes,4,rep,name=segment_refs,json=segmentRefs,proto3" json:"segment_refs,omitempty"`
	SegmentRuns   []*SegmentRun          `protobuf:"bytes,5,rep,name=segment_runs,json=segmentRuns,proto3" json:"segment_runs,omitempty"` // compact run encoding; preferred over segment_refs when present
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Par2FileReference) Reset() {
	*x = Par2FileReference{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Par2FileReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Par2FileReference) ProtoMessage() {}

func (x *Par2FileReference) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Par2FileReference.ProtoReflect.Descriptor instead.
func (*Par2FileReference) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *Par2FileReference) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Par2FileReference) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Par2FileReference) GetSegmentData() []*SegmentData {
	if x != nil {
		return x.SegmentData
	}
	return nil
}

func (x *Par2FileReference) GetSegmentRefs() []*SegmentRef {
	if x != nil {
		return x.SegmentRefs
	}
	return nil
}

func (x *Par2FileReference) GetSegmentRuns() []*SegmentRun {
	if x != nil {
		return x.SegmentRuns
	}
	return nil
}

// NestedSegmentSource represents one inner RAR volume's contribution to a nested file.
// Used when a file is inside an inner RAR that is itself inside an outer RAR.
type NestedSegmentSource struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Segments        []*SegmentData         `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`                                         // Outer RAR segments covering this inner volume
	AesKey          []byte                 `protobuf:"bytes,2,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`                               // Outer AES key (empty if unencrypted)
	AesIv           []byte                 `protobuf:"bytes,3,opt,name=aes_iv,json=aesIv,proto3" json:"aes_iv,omitempty"`                                  // Outer AES IV
	InnerOffset     int64                  `protobuf:"varint,4,opt,name=inner_offset,json=innerOffset,proto3" json:"inner_offset,omitempty"`               // Offset within decrypted inner volume where file data starts
	InnerLength     int64                  `protobuf:"varint,5,opt,name=inner_length,json=innerLength,proto3" json:"inner_length,omitempty"`               // Bytes of target file in this source
	InnerVolumeSize int64                  `protobuf:"varint,6,opt,name=inner_volume_size,json=innerVolumeSize,proto3" json:"inner_volume_size,omitempty"` // Total decrypted size of inner volume (for AES cipher)
	// When > 0 the `segments`, `aes_key`, `aes_iv`, `inner_volume_size`
	// fields above are intentionally left empty on disk and inherit from
	// FileMetadata.shared_outer_sources[shared_outer_source_index - 1].
	// Only `inner_offset` and `inner_length` are stored per-extent. 0
	// (proto default) means "no sharing" — identical to the legacy on-disk
	// layout, so old .meta files keep working without migration.
	SharedOuterSourceIndex int32         `protobuf:"varint,7,opt,name=shared_outer_source_index,json=sharedOuterSourceIndex,proto3" json:"shared_outer_source_index,omitempty"`
	SegmentRefs            []*SegmentRef `protobuf:"bytes,8,rep,name=segment_refs,json=segmentRefs,proto3" json:"segment_refs,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NestedSegmentSource) Reset() {
	*x = NestedSegmentSource{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedSegmentSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedSegmentSource) ProtoMessage() {}

func (x *NestedSegmentSource) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedSegmentSource.ProtoReflect.Descriptor instead.
func (*NestedSegmentSource) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *NestedSegmentSource) GetSegments() []*SegmentData {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *NestedSegmentSource) GetAesKey() []byte {
	if x != nil {
		return x.AesKey
	}
	return nil
}

func (x *NestedSegmentSource) GetAesIv() []byte {
	if x != nil {
		return x.AesIv
	}
	return nil
}

func (x *NestedSegmentSource) GetInnerOffset() int64 {
	if x != nil {
		return x.InnerOffset
	}
	return 0
}

func (x *NestedSegmentSource) GetInnerLength() int64 {
	if x != nil {
		return x.InnerLength
	}
	return 0
}

func (x *NestedSegmentSource) GetInnerVolumeSize() int64 {
	if x != nil {
		return x.InnerVolumeSize
	}
	return 0
}

func (x *NestedSegmentSource) GetSharedOuterSourceIndex() int32 {
	if x != nil {
		return x.SharedOuterSourceIndex
	}
	return 0
}

func (x *NestedSegmentSource) GetSegmentRefs() []*SegmentRef {
	if x != nil {
		return x.SegmentRefs
	}
	return nil
}

// ClipBoundary is one clip in a byte-concatenated multi-clip BD main feature.
// byte_len is the clip's size in the virtual file (a whole number of 192-byte
// BDAV source packets). delta_90k is the signed 90 kHz offset added to PTS/DTS
// (and delta_90k to the 90 kHz-equivalent of PCR base) for packets inside this
// clip's byte range, lifting the clip onto the unified continuous timeline.
type ClipBoundary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ByteLen       int64                  `protobuf:"varint,1,opt,name=byte_len,json=byteLen,proto3" json:"byte_len,omitempty"`
	Delta_90K     int64                  `protobuf:"varint,2,opt,name=delta_90k,json=delta90k,proto3" json:"delta_90k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipBoundary) Reset() {
	*x = ClipBoundary{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipBoundary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipBoundary) ProtoMessage() {}

func (x *ClipBoundary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipBoundary.ProtoReflect.Descriptor instead.
func (*ClipBoundary) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *ClipBoundary) GetByteLen() int64 {
	if x != nil {
		return x.ByteLen
	}
	return 0
}

func (x *ClipBoundary) GetDelta_90K() int64 {
	if x != nil {
		return x.Delta_90K
	}
	return 0
}

// HoleRun is the legacy pre-PR3 persisted hole representation. Existing rows
// are unverified and quarantined: they must not authorize padding or health
// classification until the planned migration establishes durable evidence.
type HoleRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartSegment  int64                  `protobuf:"varint,1,opt,name=start_segment,json=startSegment,proto3" json:"start_segment,omitempty"` // first missing segment index
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                                   // number of consecutive missing segments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoleRun) Reset() {
	*x = HoleRun{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoleRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoleRun) ProtoMessage() {}

func (x *HoleRun) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoleRun.ProtoReflect.Descriptor instead.
func (*HoleRun) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *HoleRun) GetStartSegment() int64 {
	if x != nil {
		return x.StartSegment
	}
	return 0
}

func (x *HoleRun) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// FileMetadata represents a single virtual file in the filesystem
// The filename comes from the actual metadata filename on disk
type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileSize      int64                  `protobuf:"varint,1,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`                 // Size of the virtual file in bytes
	SourceNzbPath string                 `protobuf:"bytes,2,opt,name=source_nzb_path,json=sourceNzbPath,proto3" json:"source_nzb_path,omitempty"` // Path to source NZB file
	Status        FileStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=metadata.FileStatus" json:"status,omitempty"`            // Health status of the file
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`              // Unix timestamp when metadata was created
	ModifiedAt    int64                  `protobuf:"varint,5,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`           // Unix timestamp when last modified
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`                                  // Password for rclone encrypted files
	Salt          string                 `protobuf:"bytes,7,opt,name=salt,proto3" json:"salt,omitempty"`                                          // Salt for rclone encrypted files
	Encryption    Encryption             `protobuf:"varint,8,opt,name=encryption,proto3,enum=metadata.Encryption" json:"encryption,omitempty"`    // Encryption type used for the file
	SegmentData   []*SegmentData         `protobuf:"bytes,9,rep,name=segment_data,json=segmentData,proto3" json:"segment_data,omitempty"`         // Segment information (lazy-loaded)
	AesKey        []byte                 `protobuf:"bytes,10,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`                       // AES encryption key (for AES-encrypted archives)
	AesIv         []byte                 `protobuf:"bytes,11,opt,name=aes_iv,json=aesIv,proto3" json:"aes_iv,omitempty"`                          // AES initialization vector (for AES-encrypted archives)
	ReleaseDate   int64                  `protobuf:"varint,12,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`       // Unix timestamp of the original Usenet post release date
	Par2Files     []*Par2FileReference   `protobuf:"bytes,13,rep,name=par2_files,json=par2Files,proto3" json:"par2_files,omitempty"`              // Associated PAR2 repair files
	NzbdavId      string                 `protobuf:"bytes,14,opt,name=nzbdav_id,json=nzbdavId,proto3" json:"nzbdav_id,omitempty"`                 // ID to maintain compatibility with nzbdav
	NestedSources []*NestedSegmentSource `protobuf:"bytes,15,rep,name=nested_sources,json=nestedSources,proto3" json:"nested_sources,omitempty"`  // Nested RAR sources (when file is inside inner RAR within outer RAR)
	// Per-clip timeline table for Blu-ray main-feature virtual files that
	// byte-concatenate multiple M2TS clips (each with its own independent
	// PTS/DTS/PCR base). At read time a TS-aware filter adds each clip's
	// delta_90k to the timestamps inside that clip's byte range, producing a
	// single continuous timeline so ffprobe/players report the correct
	// duration and seek accurately. Empty for every other file type, which
	// disables the filter entirely (zero overhead, total safety).
	ClipBoundaries []*ClipBoundary `protobuf:"bytes,17,rep,name=clip_boundaries,json=clipBoundaries,proto3" json:"clip_boundaries,omitempty"`
	// Outer sources shared by groups of NestedSegmentSource entries.
	// Used for multi-extent encrypted volumes — e.g. a Blu-ray main feature
	// with hundreds of extents that all read from the same encrypted RAR.
	// Each entry holds the full Segments + AesKey + AesIv + InnerVolumeSize
	// once; the corresponding NestedSegmentSource entries reference it by
	// 1-based index via shared_outer_source_index, storing only
	// inner_offset + inner_length per-extent. Cuts the on-disk .meta size
	// from O(extents * segments) to O(extents + segments) for these files.
	SharedOuterSources []*NestedSegmentSource `protobuf:"bytes,16,rep,name=shared_outer_sources,json=sharedOuterSources,proto3" json:"shared_outer_sources,omitempty"`
	StoreRef           string                 `protobuf:"bytes,18,opt,name=store_ref,json=storeRef,proto3" json:"store_ref,omitempty"`          // id/path of the shared NzbStore
	SegmentRefs        []*SegmentRef          `protobuf:"bytes,19,rep,name=segment_refs,json=segmentRefs,proto3" json:"segment_refs,omitempty"` // v3 replacement for segment_data
	SegmentRuns        []*SegmentRun          `protobuf:"bytes,20,rep,name=segment_runs,json=segmentRuns,proto3" json:"segment_runs,omitempty"` // compact run encoding; preferred over segment_refs when present
	KnownHoles         []*HoleRun             `protobuf:"bytes,21,rep,name=known_holes,json=knownHoles,proto3" json:"known_holes,omitempty"`    // legacy unverified holes; quarantined pending migration
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *FileMetadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileMetadata) GetSourceNzbPath() string {
	if x != nil {
		return x.SourceNzbPath
	}
	return ""
}

func (x *FileMetadata) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_STATUS_UNSPECIFIED
}

func (x *FileMetadata) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FileMetadata) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

func (x *FileMetadata) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *FileMetadata) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *FileMetadata) GetEncryption() Encryption {
	if x != nil {
		return x.Encryption
	}
	return Encryption_NONE
}

func (x *FileMetadata) GetSegmentData() []*SegmentData {
	if x != nil {
		return x.SegmentData
	}
	return nil
}

func (x *FileMetadata) GetAesKey() []byte {
	if x != nil {
		return x.AesKey
	}
	return nil
}

func (x *FileMetadata) GetAesIv() []byte {
	if x != nil {
		return x.AesIv
	}
	return nil
}

func (x *FileMetadata) GetReleaseDate() int64 {
	if x != nil {
		return x.ReleaseDate
	}
	return 0
}

func (x *FileMetadata) GetPar2Files() []*Par2FileReference {
	if x != nil {
		return x.Par2Files
	}
	return nil
}

func (x *FileMetadata) GetNzbdavId() string {
	if x != nil {
		return x.NzbdavId
	}
	return ""
}

func (x *FileMetadata) GetNestedSources() []*NestedSegmentSource {
	if x != nil {
		return x.NestedSources
	}
	return nil
}

func (x *FileMetadata) GetClipBoundaries() []*ClipBoundary {
	if x != nil {
		return x.ClipBoundaries
	}
	return nil
}

func (x *FileMetadata) GetSharedOuterSources() []*NestedSegmentSource {
	if x != nil {
		return x.SharedOuterSources
	}
	return nil
}

func (x *FileMetadata) GetStoreRef() string {
	if x != nil {
		return x.StoreRef
	}
	return ""
}

func (x *FileMetadata) GetSegmentRefs() []*SegmentRef {
	if x != nil {
		return x.SegmentRefs
	}
	return nil
}

func (x *FileMetadata) GetSegmentRuns() []*SegmentRun {
	if x != nil {
		return x.SegmentRuns
	}
	return nil
}

func (x *FileMetadata) GetKnownHoles() []*HoleRun {
	if x != nil {
		return x.KnownHoles
	}
	return nil
}

// NzbStore is the complete original NZB for a release, stored zstd-compressed at
// the (renamed) source_nzb_path. Single source of truth for streaming + NZB regen.
type NzbStore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*NzbFileEntry        `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"` // original <file>s, in NZB order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NzbStore) Reset() {
	*x = NzbStore{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NzbStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NzbStore) ProtoMessage() {}

func (x *NzbStore) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NzbStore.ProtoReflect.Descriptor instead.
func (*NzbStore) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *NzbStore) GetFiles() []*NzbFileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

type NzbFileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Poster        string                 `protobuf:"bytes,2,opt,name=poster,proto3" json:"poster,omitempty"`
	Date          int64                  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"` // unix ts
	Groups        []string               `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	Segments      []*NzbSeg              `protobuf:"bytes,5,rep,name=segments,proto3" json:"segments,omitempty"` // ordered by `number`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NzbFileEntry) Reset() {
	*x = NzbFileEntry{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NzbFileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NzbFileEntry) ProtoMessage() {}

func (x *NzbFileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NzbFileEntry.ProtoReflect.Descriptor instead.
func (*NzbFileEntry) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *NzbFileEntry) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NzbFileEntry) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

func (x *NzbFileEntry) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *NzbFileEntry) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *NzbFileEntry) GetSegments() []*NzbSeg {
	if x != nil {
		return x.Segments
	}
	return nil
}

type NzbSeg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // message-id (no angle brackets)
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Bytes         int64                  `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NzbSeg) Reset() {
	*x = NzbSeg{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NzbSeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NzbSeg) ProtoMessage() {}

func (x *NzbSeg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NzbSeg.ProtoReflect.Descriptor instead.
func (*NzbSeg) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{8}
}

func (x *NzbSeg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NzbSeg) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *NzbSeg) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

// SegmentRef points into the flat segment index of the release's NzbStore.
type SegmentRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreIndex    int64                  `protobuf:"varint,1,opt,name=store_index,json=storeIndex,proto3" json:"store_index,omitempty"`    // flat index: files-in-order then segments-by-number
	StartOffset   int64                  `protobuf:"varint,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"` // usable byte range within that segment
	EndOffset     int64                  `protobuf:"varint,3,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	DecodedBytes  int64                  `protobuf:"varint,4,opt,name=decoded_bytes,json=decodedBytes,proto3" json:"decoded_bytes,omitempty"` // actual decoded segment size; 0 means use NzbSeg.bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentRef) Reset() {
	*x = SegmentRef{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentRef) ProtoMessage() {}

func (x *SegmentRef) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentRef.ProtoReflect.Descriptor instead.
func (*SegmentRef) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{9}
}

func (x *SegmentRef) GetStoreIndex() int64 {
	if x != nil {
		return x.StoreIndex
	}
	return 0
}

func (x *SegmentRef) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *SegmentRef) GetEndOffset() int64 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *SegmentRef) GetDecodedBytes() int64 {
	if x != nil {
		return x.DecodedBytes
	}
	return 0
}

// SegmentRun compactly encodes a consecutive range of full-segment refs:
// start_offset=0, end_offset=decoded_bytes-1, store_index increasing by 1.
// Used in place of repeated SegmentRef when a file's segments map 1:1 onto a
// contiguous run of the NzbStore (the common non-archive case).
type SegmentRun struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BaseStoreIndex int64                  `protobuf:"varint,1,opt,name=base_store_index,json=baseStoreIndex,proto3" json:"base_store_index,omitempty"` // flat store index of the first segment in the run
	Count          int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                                           // number of consecutive segments
	DecodedBytes   int64                  `protobuf:"varint,3,opt,name=decoded_bytes,json=decodedBytes,proto3" json:"decoded_bytes,omitempty"`         // decoded size shared by every segment in the run; 0 = use NzbSeg.bytes
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SegmentRun) Reset() {
	*x = SegmentRun{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentRun) ProtoMessage() {}

func (x *SegmentRun) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentRun.ProtoReflect.Descriptor instead.
func (*SegmentRun) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{10}
}

func (x *SegmentRun) GetBaseStoreIndex() int64 {
	if x != nil {
		return x.BaseStoreIndex
	}
	return 0
}

func (x *SegmentRun) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SegmentRun) GetDecodedBytes() int64 {
	if x != nil {
		return x.DecodedBytes
	}
	return 0
}

var File_internal_metadata_proto_metadata_proto protoreflect.FileDescriptor

const file_internal_metadata_proto_metadata_proto_rawDesc = "" +
	"\n" +
	"&internal/metadata/proto/metadata.proto\x12\bmetadata\"\x82\x01\n" +
	"\vSegmentData\x12!\n" +
	"\fsegment_size\x18\x01 \x01(\x03R\vsegmentSize\x12!\n" +
	"\fstart_offset\x18\x03 \x01(\x03R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x04 \x01(\x03R\tendOffset\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\"\xf8\x01\n" +
	"\x11Par2FileReference\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\x128\n" +
	"\fsegment_data\x18\x03 \x03(\v2\x15.metadata.SegmentDataR\vsegmentData\x127\n" +
	"\fsegment_refs\x18\x04 \x03(\v2\x14.metadata.SegmentRefR\vsegmentRefs\x127\n" +
	"\fsegment_runs\x18\x05 \x03(\v2\x14.metadata.SegmentRunR\vsegmentRuns\"\xde\x02\n" +
	"\x13NestedSegmentSource\x121\n" +
	"\bsegments\x18\x01 \x03(\v2\x15.metadata.SegmentDataR\bsegments\x12\x17\n" +
	"\aaes_key\x18\x02 \x01(\fR\x06aesKey\x12\x15\n" +
	"\x06aes_iv\x18\x03 \x01(\fR\x05aesIv\x12!\n" +
	"\finner_offset\x18\x04 \x01(\x03R\vinnerOffset\x12!\n" +
	"\finner_length\x18\x05 \x01(\x03R\vinnerLength\x12*\n" +
	"\x11inner_volume_size\x18\x06 \x01(\x03R\x0finnerVolumeSize\x129\n" +
	"\x19shared_outer_source_index\x18\a \x01(\x05R\x16sharedOuterSourceIndex\x127\n" +
	"\fsegment_refs\x18\b \x03(\v2\x14.metadata.SegmentRefR\vsegmentRefs\"F\n" +
	"\fClipBoundary\x12\x19\n" +
	"\bbyte_len\x18\x01 \x01(\x03R\abyteLen\x12\x1b\n" +
	"\tdelta_90k\x18\x02 \x01(\x03R\bdelta90k\"D\n" +
	"\aHoleRun\x12#\n" +
	"\rstart_segment\x18\x01 \x01(\x03R\fstartSegment\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xa8\a\n" +
	"\fFileMetadata\x12\x1b\n" +
	"\tfile_size\x18\x01 \x01(\x03R\bfileSize\x12&\n" +
	"\x0fsource_nzb_path\x18\x02 \x01(\tR\rsourceNzbPath\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.metadata.FileStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vmodified_at\x18\x05 \x01(\x03R\n" +
	"modifiedAt\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x12\n" +
	"\x04salt\x18\a \x01(\tR\x04salt\x124\n" +
	"\n" +
	"encryption\x18\b \x01(\x0e2\x14.metadata.EncryptionR\n" +
	"encryption\x128\n" +
	"\fsegment_data\x18\t \x03(\v2\x15.metadata.SegmentDataR\vsegmentData\x12\x17\n" +
	"\aaes_key\x18\n" +
	" \x01(\fR\x06aesKey\x12\x15\n" +
	"\x06aes_iv\x18\v \x01(\fR\x05aesIv\x12!\n" +
	"\frelease_date\x18\f \x01(\x03R\vreleaseDate\x12:\n" +
	"\n" +
	"par2_files\x18\r \x03(\v2\x1b.metadata.Par2FileReferenceR\tpar2Files\x12\x1b\n" +
	"\tnzbdav_id\x18\x0e \x01(\tR\bnzbdavId\x12D\n" +
	"\x0enested_sources\x18\x0f \x03(\v2\x1d.metadata.NestedSegmentSourceR\rnestedSources\x12?\n" +
	"\x0fclip_boundaries\x18\x11 \x03(\v2\x16.metadata.ClipBoundaryR\x0eclipBoundaries\x12O\n" +
	"\x14shared_outer_sources\x18\x10 \x03(\v2\x1d.metadata.NestedSegmentSourceR\x12sharedOuterSources\x12\x1b\n" +
	"\tstore_ref\x18\x12 \x01(\tR\bstoreRef\x127\n" +
	"\fsegment_refs\x18\x13 \x03(\v2\x14.metadata.SegmentRefR\vsegmentRefs\x127\n" +
	"\fsegment_runs\x18\x14 \x03(\v2\x14.metadata.SegmentRunR\vsegmentRuns\x122\n" +
	"\vknown_holes\x18\x15 \x03(\v2\x11.metadata.HoleRunR\n" +
	"knownHoles\"8\n" +
	"\bNzbStore\x12,\n" +
	"\x05files\x18\x01 \x03(\v2\x16.metadata.NzbFileEntryR\x05files\"\x9a\x01\n" +
	"\fNzbFileEntry\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06poster\x18\x02 \x01(\tR\x06poster\x12\x12\n" +
	"\x04date\x18\x03 \x01(\x03R\x04date\x12\x16\n" +
	"\x06groups\x18\x04 \x03(\tR\x06groups\x12,\n" +
	"\bsegments\x18\x05 \x03(\v2\x10.metadata.NzbSegR\bsegments\"F\n" +
	"\x06NzbSeg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x03R\x05bytes\"\x94\x01\n" +
	"\n" +
	"SegmentRef\x12\x1f\n" +
	"\vstore_index\x18\x01 \x01(\x03R\n" +
	"storeIndex\x12!\n" +
	"\fstart_offset\x18\x02 \x01(\x03R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x03 \x01(\x03R\tendOffset\x12#\n" +
	"\rdecoded_bytes\x18\x04 \x01(\x03R\fdecodedBytes\"q\n" +
	"\n" +
	"SegmentRun\x12(\n" +
	"\x10base_store_index\x18\x01 \x01(\x03R\x0ebaseStoreIndex\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12#\n" +
	"\rdecoded_bytes\x18\x03 \x01(\x03R\fdecodedBytes*8\n" +
	"\n" +
	"Encryption\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06RCLONE\x10\x01\x12\v\n" +
	"\aHEADERS\x10\x02\x12\a\n" +
	"\x03AES\x10\x03*w\n" +
	"\n" +
	"FileStatus\x12\x1b\n" +
	"\x17FILE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FILE_STATUS_HEALTHY\x10\x01\x12\x19\n" +
	"\x15FILE_STATUS_CORRUPTED\x10\x03\x12\x18\n" +
	"\x14FILE_STATUS_DEGRADED\x10\x04B\x04Z\x02./b\x06proto3"

var (
	file_internal_metadata_proto_metadata_proto_rawDescOnce sync.Once
	file_internal_metadata_proto_metadata_proto_rawDescData []byte
)

func file_internal_metadata_proto_metadata_proto_rawDescGZIP() []byte {
	file_internal_metadata_proto_metadata_proto_rawDescOnce.Do(func() {
		file_internal_metadata_proto_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_metadata_proto_metadata_proto_rawDesc), len(file_internal_metadata_proto_metadata_proto_rawDesc)))
	})
	return file_internal_metadata_proto_metadata_proto_rawDescData
}

var file_internal_metadata_proto_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_metadata_proto_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_metadata_proto_metadata_proto_goTypes = []any{
	(Encryption)(0),             // 0: metadata.Encryption
	(FileStatus)(0),             // 1: metadata.FileStatus
	(*SegmentData)(nil),         // 2: metadata.SegmentData
	(*Par2FileReference)(nil),   // 3: metadata.Par2FileReference
	(*NestedSegmentSource)(nil), // 4: metadata.NestedSegmentSource
	(*ClipBoundary)(nil),        // 5: metadata.ClipBoundary
	(*HoleRun)(nil),             // 6: metadata.HoleRun
	(*FileMetadata)(nil),        // 7: metadata.FileMetadata
	(*NzbStore)(nil),            // 8: metadata.NzbStore
	(*NzbFileEntry)(nil),        // 9: metadata.NzbFileEntry
	(*NzbSeg)(nil),              // 10: metadata.NzbSeg
	(*SegmentRef)(nil),          // 11: metadata.SegmentRef
	(*SegmentRun)(nil),          // 12: metadata.SegmentRun
}
var file_internal_metadata_proto_metadata_proto_depIdxs = []int32{
	2,  // 0: metadata.Par2FileReference.segment_data:type_name -> metadata.SegmentData
	11, // 1: metadata.Par2FileReference.segment_refs:type_name -> metadata.SegmentRef
	12, // 2: metadata.Par2FileReference.segment_runs:type_name -> metadata.SegmentRun
	2,  // 3: metadata.NestedSegmentSource.segments:type_name -> metadata.SegmentData
	11, // 4: metadata.NestedSegmentSource.segment_refs:type_name -> metadata.SegmentRef
	1,  // 5: metadata.FileMetadata.status:type_name -> metadata.FileStatus
	0,  // 6: metadata.FileMetadata.encryption:type_name -> metadata.Encryption
	2,  // 7: metadata.FileMetadata.segment_data:type_name -> metadata.SegmentData
	3,  // 8: metadata.FileMetadata.par2_files:type_name -> metadata.Par2FileReference
	4,  // 9: metadata.FileMetadata.nested_sources:type_name -> metadata.NestedSegmentSource
	5,  // 10: metadata.FileMetadata.clip_boundaries:type_name -> metadata.ClipBoundary
	4,  // 11: metadata.FileMetadata.shared_outer_sources:type_name -> metadata.NestedSegmentSource
	11, // 12: metadata.FileMetadata.segment_refs:type_name -> metadata.SegmentRef
	12, // 13: metadata.FileMetadata.segment_runs:type_name -> metadata.SegmentRun
	6,  // 14: metadata.FileMetadata.known_holes:type_name -> metadata.HoleRun
	9,  // 15: metadata.NzbStore.files:type_name -> metadata.NzbFileEntry
	10, // 16: metadata.NzbFileEntry.segments:type_name -> metadata.NzbSeg
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_metadata_proto_metadata_proto_init() }
func file_internal_metadata_proto_metadata_proto_init() {
	if File_internal_metadata_proto_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_metadata_proto_metadata_proto_rawDesc), len(file_internal_metadata_proto_metadata_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_metadata_proto_metadata_proto_goTypes,
		DependencyIndexes: file_internal_metadata_proto_metadata_proto_depIdxs,
		EnumInfos:         file_internal_metadata_proto_metadata_proto_enumTypes,
		MessageInfos:      file_internal_metadata_proto_metadata_proto_msgTypes,
	}.Build()
	File_internal_metadata_proto_metadata_proto = out.File
	file_internal_metadata_proto_metadata_proto_goTypes = nil
	file_internal_metadata_proto_metadata_proto_depIdxs = nil
}
